
device: 'cpu'  #'cuda' #
ch_gap: 8 #16 #
frame_batch_size: 1
enlarge_factor: 60
cluster_number: 4
comp_max: 8
max_iter: 2
wave_idx: 1 #1 #0
num_scale: 1e12 #1e6 #
tx_gaps: [1, 2, 3, 4] #5, 6, 8, 10, 12]
frame_num: 10
dat_num: 2
intersect_method: 'gt'
phase_refinement_opt: True
radial_offset_method: 'off'
parity_opt: True
echo_treshold: 0.0825
dist_par_threshold: 0.5
shift_factor: 3.4 #4.0

logging: False
plt_comp_opt: False
plt_frame_opt: False
save_opt: False

data_path: PALA_data_InSilicoFlow/  #PALA_data_InVivoRatBrain #
ubx_dir: /storage/homefs/ch21z139/PALA_dataset/${data_path}
map_dir: /home/chris/LocalDatasets/03_PALA/${data_path}
data_dir: ${map_dir}